#		███████╗████████╗ ██████╗ ███╗   ██╗███████╗     █████╗ ██╗  ████████╗ █████╗ ██████╗ 
#		██╔════╝╚══██╔══╝██╔═══██╗████╗  ██║██╔════╝    ██╔══██╗██║  ╚══██╔══╝██╔══██╗██╔══██╗
#		███████╗   ██║   ██║   ██║██╔██╗ ██║█████╗      ███████║██║     ██║   ███████║██████╔╝
#		╚════██║   ██║   ██║   ██║██║╚██╗██║██╔══╝      ██╔══██║██║     ██║   ██╔══██║██╔══██╗
#		███████║   ██║   ╚██████╔╝██║ ╚████║███████╗    ██║  ██║███████╗██║   ██║  ██║██║  ██║
#		╚══════╝   ╚═╝    ╚═════╝ ╚═╝  ╚═══╝╚══════╝    ╚═╝  ╚═╝╚══════╝╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝

altar-spawn:
  - ''
  - '&d&l[ALTAR MISTICO] &fUm altar misterioso apareceu na arena.'
  - ''
