#
#	  ______   ____  _____   ___   ____      ____   _______  _____  _____  _____   ______  _____  ____  _____   ______   
#	.' ____ \ |_   \|_   _|.'   `.|_  _|    |_  _| |_   __ \|_   _||_   _||_   _|.' ___  ||_   _||_   \|_   _|.' ____ \  
#	| (___ \_|  |   \ | | /  .-.  \ \ \  /\  / /     | |__) | | |    | |    | | / .'   \_|  | |    |   \ | |  | (___ \_| 
#	 _.____`.   | |\ \| | | |   | |  \ \/  \/ /      |  ___/  | |   _| '    ' | | |   ____  | |    | |\ \| |   _.____`.  
#	| \____) | _| |_\   |_\  `-'  /   \  /\  /      _| |_    _| |__/ |\ \__/ /  \ `.___]  |_| |_  _| |_\   |_ | \____) | 
#	 \______.'|_____|\____|`.___.'     \/  \/      |_____|  |________| `.__.'    `._____.'|_____||_____|\____| \______.'
#
#

Horario:
  Nether: "15:00:00"

NetherBoss:
  NOME: "§6§lHADES"
  HP: 2000

Cavaleiro:
  HP: 500
  quantidade: 2

Servos:
  HP: 100
  quantidade: 40
  
Carminidio:
  HP: 50
  quantidade: 10
  
# desafio.desconto.vip
reparar-custo: 100000000
desconto:
  vip: 10

#LOJA PREÇOS
carminita_espada: 60
picareta_ember: 50
carminita_pa: 42
carminita_empunhadura: 10
ember_cabo: 15
carminita_barra: 20
ember_cristal: 6